openapi: "3.0.0"
info:
  description: "This is a running template that will eventually be used for BetterCloud OAS files and for unit testing"
  version: 1.0.0
  title: BetterCloud's Template OAS File
  license:
    name: MIT
  contact:
    email: "devx@bettercloud.com"
    name: "DevX"
servers:
  - url: https://petstore.bettercloud.com/capability/v1
tags:
  - name: "pets"
paths:
  /pets:
    description: "Operations for the Pet resource"
    get:
      summary: List all pets
      description: "List all pets"
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Wrapper for pet request
          required: false
          schema:
            format: int32
            type: integer
          example: 123
      requestBody:
        description: 'B'
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PetRequest"
            example:
              petId: 234
      responses:
        "200":
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
              example:
                - breedId: 123
                  name: "Fido"
                  breed: POODLE
        "401":
          description: Unauthorized
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "404":
          description: Not Found
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "429":
          description: Too many requests
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "500":
          description: Internal Server Error
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
    post:
      summary: Create a pet
      description: "Creates a pet resource"
      operationId: createPets
      tags:
        - pets
      responses:
        "201":
          description: Should we allow null response bodies when applicable?
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
              example:
                - breedId: 123
                  name: "Fido"
                  breed: POODLE
                - breedId: 1234
                  name: "Bo"
                  breed: POODLE
        "401":
          description: Unauthorized
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "404":
          description: Not Found
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "429":
          description: Too many requests
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "500":
          description: Internal Server Error
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
  /testing-kebab/{petId}:
    description: "Operations for a specific pet identified by petId"
    get:
      summary: Info for a specific pet
      description: "Retrieve details for a specific pet"
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
          example: "1234"
        - name: Accept-Language
          in: header
          description: "Ut consequat ipsum sit amet ullamcorper congue. Vivamus consequat molestie erat, quis pulvinar eros. Donec non tellus quis neque pretium scelerisque. "
          required: true
          style: simple
          explode: false
          schema:
            type: string
          example: "en"
      responses:
        "200":
          description: Expected response to a valid request
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
              example:
                breedId: 123
                name: "Bojangles"
                breed: POODLE
        "401":
          description: Unauthorized
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "404":
          description: Not Found
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "429":
          description: Too many requests
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        "500":
          description: Internal Server Error
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-ID:
              content:
                text/plain:
                  schema:
                    type: string
                  example: default-global
            X-Rate-Limit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '491'
            X-Rate-Limit-Reset:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '09/14/2018 17:57:24'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
                - code: 40000
                  description: "test test test"
                  helpLink: "https://testtestetestestestsetsetsetestes"
components:
  schemas:
    Pet:
      type: object
      required:
        - breedId
        - name
        - breed
      properties:
        testTimestamp:
          format: date-time
          type: string
        name:
          type: string
        breed:
          type: string
          enum:
            - POODLE
            - BERNESE_MOUNTAIN_DOG
            - CHIHUAHUA
            - WEST_HIGHLAND_TERRIER
            - IRISH_WOLF_HOUND
        tag:
          type: string
      example:
        breedId: 123
        name: Bobo
        breed: POODLE
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
      example:
        - breedId: 123
          name: Bobo
          breed: POODLE
        - breedId: 123
          name: Bobo
          breed: POODLE
    Error:
      type: object
      required:
        - code
        - description
        - helpLink
      properties:
        code:
          type: integer
          format: int32
        description:
          type: string
        helpLink:
          type: string
      example:
        code: 40000
        description: "test test test"
        helpLink: "https://testtestetestestestsetsetsetestes"
    Errors:
      type: array
      items:
        $ref: "#/components/schemas/Error"
      example:
        - code: 40000
          description: "test test test"
          helpLink: "https://testtestetestestestsetsetsetestes"
        - code: 40000
          description: "test test test"
          helpLink: "https://testtestetestestestsetsetsetestes"
    PetRequest:
      type: object
      required:
        - petId
      properties:
        petId:
          type: integer
          format: int32
        tag:
          type: string
      example:
        petId: 123